# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/hashicorp/nomad-openapi/main/v1/openapi.yaml

from __future__ import annotations

from typing import Annotated, Any

from pydantic import AwareDatetime, Base64Str, BaseModel, Field, RootModel
from typing_extensions import TypeAliasType


class ACLPolicyListStub(BaseModel):
    CreateIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    Description: str | None = None
    ModifyIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    Name: str | None = None


class ACLTokenRoleLink(BaseModel):
    ID: str | None = None
    Name: str | None = None


class Affinity(BaseModel):
    LTarget: str | None = None
    Operand: str | None = None
    RTarget: str | None = None
    Weight: Annotated[int | None, Field(ge=-128, le=127)] = None


class AllocDeploymentStatus(BaseModel):
    Canary: bool | None = None
    Healthy: bool | None = None
    ModifyIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    Timestamp: AwareDatetime | None = None


class AllocStopResponse(BaseModel):
    EvalID: str | None = None
    Index: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None


class AllocatedCpuResources(BaseModel):
    CpuShares: int | None = None


class AllocatedDeviceResource(BaseModel):
    DeviceIDs: list[str] | None = None
    Name: str | None = None
    Type: str | None = None
    Vendor: str | None = None


class AllocatedMemoryResources(BaseModel):
    MemoryMB: int | None = None
    MemoryMaxMB: int | None = None


class Attribute(BaseModel):
    Bool: bool | None = None
    Float: float | None = None
    Int: int | None = None
    String: str | None = None
    Unit: str | None = None


class AutopilotConfiguration(BaseModel):
    CleanupDeadServers: bool | None = None
    CreateIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    DisableUpgradeMigration: bool | None = None
    EnableCustomUpgrades: bool | None = None
    EnableRedundancyZones: bool | None = None
    LastContactThreshold: str | None = None
    MaxTrailingLogs: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    MinQuorum: Annotated[int | None, Field(ge=0)] = None
    ModifyIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    ServerStabilizationTime: str | None = None


class CSIControllerInfo(BaseModel):
    SupportsAttachDetach: bool | None = None
    SupportsClone: bool | None = None
    SupportsCondition: bool | None = None
    SupportsCreateDelete: bool | None = None
    SupportsCreateDeleteSnapshot: bool | None = None
    SupportsExpand: bool | None = None
    SupportsGet: bool | None = None
    SupportsGetCapacity: bool | None = None
    SupportsListSnapshots: bool | None = None
    SupportsListVolumes: bool | None = None
    SupportsListVolumesAttachedNodes: bool | None = None
    SupportsReadOnlyAttach: bool | None = None


class CSIMountOptions(BaseModel):
    FSType: str | None = None
    MountFlags: list[str] | None = None


class CSIPluginListStub(BaseModel):
    ControllerRequired: bool | None = None
    ControllersExpected: int | None = None
    ControllersHealthy: int | None = None
    CreateIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    ID: str | None = None
    ModifyIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    NodesExpected: int | None = None
    NodesHealthy: int | None = None
    Provider: str | None = None


class CSIPluginType(RootModel[str]):
    root: str


class CSISecrets(RootModel[dict[str, str]]):
    root: dict[str, str]


class CSISnapshot(BaseModel):
    CreateTime: int | None = None
    ExternalSourceVolumeID: str | None = None
    ID: str | None = None
    IsReady: bool | None = None
    Name: str | None = None
    Parameters: dict[str, str] | None = None
    PluginID: str | None = None
    Secrets: CSISecrets | None = None
    SizeBytes: int | None = None
    SourceVolumeID: str | None = None


class CSISnapshotCreateRequest(BaseModel):
    Namespace: str | None = None
    Region: str | None = None
    SecretID: str | None = None
    Snapshots: list[CSISnapshot] | None = None


class CSISnapshotCreateResponse(BaseModel):
    KnownLeader: bool | None = None
    LastContact: int | None = None
    LastIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    NextToken: str | None = None
    RequestTime: int | None = None
    Snapshots: list[CSISnapshot] | None = None


class CSISnapshotListResponse(BaseModel):
    KnownLeader: bool | None = None
    LastContact: int | None = None
    LastIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    NextToken: str | None = None
    RequestTime: int | None = None
    Snapshots: list[CSISnapshot] | None = None


class CSITopology(BaseModel):
    Segments: dict[str, str] | None = None


class CSITopologyRequest(BaseModel):
    Preferred: list[CSITopology] | None = None
    Required: list[CSITopology] | None = None


class CSIVolumeAccessMode(RootModel[str]):
    root: str


class CSIVolumeAttachmentMode(RootModel[str]):
    root: str


class CSIVolumeCapability(BaseModel):
    AccessMode: str | None = None
    AttachmentMode: str | None = None


class CSIVolumeExternalStub(BaseModel):
    CapacityBytes: int | None = None
    CloneID: str | None = None
    ExternalID: str | None = None
    IsAbnormal: bool | None = None
    PublishedExternalNodeIDs: list[str] | None = None
    SnapshotID: str | None = None
    Status: str | None = None
    VolumeContext: dict[str, str] | None = None


class CSIVolumeListExternalResponse(BaseModel):
    NextToken: str | None = None
    Volumes: list[CSIVolumeExternalStub] | None = None


class CSIVolumeListStub(BaseModel):
    AccessMode: str | None = None
    AttachmentMode: str | None = None
    ControllerRequired: bool | None = None
    ControllersExpected: int | None = None
    ControllersHealthy: int | None = None
    CreateIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    CurrentReaders: int | None = None
    CurrentWriters: int | None = None
    ExternalID: str | None = None
    ID: str | None = None
    ModifyIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    Name: str | None = None
    Namespace: str | None = None
    NodesExpected: int | None = None
    NodesHealthy: int | None = None
    PluginID: str | None = None
    Provider: str | None = None
    ResourceExhausted: AwareDatetime | None = None
    Schedulable: bool | None = None
    Topologies: list[CSITopology] | None = None


class ChangeScript(BaseModel):
    Args: list[str] | None = None
    Command: str | None = None
    FailOnError: bool | None = None
    Timeout: int | None = None


class CheckRestart(BaseModel):
    Grace: int | None = None
    IgnoreWarnings: bool | None = None
    Limit: int | None = None


class Constraint(BaseModel):
    LTarget: str | None = None
    Operand: str | None = None
    RTarget: str | None = None


class Consul(BaseModel):
    Namespace: str | None = None


class ConsulExposePath(BaseModel):
    ListenerPort: str | None = None
    LocalPathPort: int | None = None
    Path: str | None = None
    Protocol: str | None = None


class ConsulGatewayBindAddress(BaseModel):
    Address: str | None = None
    Name: str | None = None
    Port: int | None = None


class ConsulGatewayProxy(BaseModel):
    Config: dict[str, Any] | None = None
    ConnectTimeout: int | None = None
    EnvoyDNSDiscoveryType: str | None = None
    EnvoyGatewayBindAddresses: dict[str, ConsulGatewayBindAddress] | None = None
    EnvoyGatewayBindTaggedAddresses: bool | None = None
    EnvoyGatewayNoDefaultBind: bool | None = None


class ConsulGatewayTLSConfig(BaseModel):
    CipherSuites: list[str] | None = None
    Enabled: bool | None = None
    TLSMaxVersion: str | None = None
    TLSMinVersion: str | None = None


class ConsulIngressService(BaseModel):
    Hosts: list[str] | None = None
    Name: str | None = None


class ConsulLinkedService(BaseModel):
    CAFile: str | None = None
    CertFile: str | None = None
    KeyFile: str | None = None
    Name: str | None = None
    SNI: str | None = None


class ConsulMeshConfigEntry(RootModel[Any]):
    root: Any


class ConsulMeshGateway(BaseModel):
    Mode: str | None = None


class ConsulTerminatingConfigEntry(BaseModel):
    Services: list[ConsulLinkedService] | None = None


class ConsulUpstream(BaseModel):
    Datacenter: str | None = None
    DestinationName: str | None = None
    DestinationNamespace: str | None = None
    LocalBindAddress: str | None = None
    LocalBindPort: int | None = None
    MeshGateway: ConsulMeshGateway | None = None


class Context(RootModel[str]):
    root: str


class DNSConfig(BaseModel):
    Options: list[str] | None = None
    Searches: list[str] | None = None
    Servers: list[str] | None = None


class DeploymentAllocHealthRequest(BaseModel):
    DeploymentID: str | None = None
    HealthyAllocationIDs: list[str] | None = None
    Namespace: str | None = None
    Region: str | None = None
    SecretID: str | None = None
    UnhealthyAllocationIDs: list[str] | None = None


class DeploymentPauseRequest(BaseModel):
    DeploymentID: str | None = None
    Namespace: str | None = None
    Pause: bool | None = None
    Region: str | None = None
    SecretID: str | None = None


class DeploymentPromoteRequest(BaseModel):
    All: bool | None = None
    DeploymentID: str | None = None
    Groups: list[str] | None = None
    Namespace: str | None = None
    Region: str | None = None
    SecretID: str | None = None


class DeploymentState(BaseModel):
    AutoRevert: bool | None = None
    DesiredCanaries: int | None = None
    DesiredTotal: int | None = None
    HealthyAllocs: int | None = None
    PlacedAllocs: int | None = None
    PlacedCanaries: list[str] | None = None
    ProgressDeadline: int | None = None
    Promoted: bool | None = None
    RequireProgressBy: AwareDatetime | None = None
    UnhealthyAllocs: int | None = None


class DeploymentUnblockRequest(BaseModel):
    DeploymentID: str | None = None
    Namespace: str | None = None
    Region: str | None = None
    SecretID: str | None = None


class DeploymentUpdateResponse(BaseModel):
    DeploymentModifyIndex: Annotated[
        int | None, Field(ge=0, le=18446744073709552000)
    ] = None
    EvalCreateIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    EvalID: str | None = None
    LastIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    RequestTime: int | None = None
    RevertedJobVersion: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = (
        None
    )


class DesiredTransition(BaseModel):
    Migrate: bool | None = None
    Reschedule: bool | None = None


class DesiredUpdates(BaseModel):
    Canary: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    DestructiveUpdate: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = (
        None
    )
    Ignore: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    InPlaceUpdate: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    Migrate: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    Place: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    Preemptions: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    Stop: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None


class DispatchPayloadConfig(BaseModel):
    File: str | None = None


class DrainMetadata(BaseModel):
    AccessorID: str | None = None
    Meta: dict[str, str] | None = None
    StartedAt: AwareDatetime | None = None
    Status: str | None = None
    UpdatedAt: AwareDatetime | None = None


class DrainSpec(BaseModel):
    Deadline: int | None = None
    IgnoreSystemJobs: bool | None = None


class DrainStatus(RootModel[str]):
    root: str


class DrainStrategy(BaseModel):
    Deadline: int | None = None
    ForceDeadline: AwareDatetime | None = None
    IgnoreSystemJobs: bool | None = None
    StartedAt: AwareDatetime | None = None


class DriverInfo(BaseModel):
    Attributes: dict[str, str] | None = None
    Detected: bool | None = None
    HealthDescription: str | None = None
    Healthy: bool | None = None
    UpdateTime: AwareDatetime | None = None


class Duration(RootModel[int]):
    root: int


class EphemeralDisk(BaseModel):
    Migrate: bool | None = None
    SizeMB: int | None = None
    Sticky: bool | None = None


class EvalOptions(BaseModel):
    ForceReschedule: bool | None = None


class EvaluationStub(BaseModel):
    BlockedEval: str | None = None
    CreateIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    CreateTime: int | None = None
    DeploymentID: str | None = None
    ID: str | None = None
    JobID: str | None = None
    ModifyIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    ModifyTime: int | None = None
    Namespace: str | None = None
    NextEval: str | None = None
    NodeID: str | None = None
    PreviousEval: str | None = None
    Priority: int | None = None
    Status: str | None = None
    StatusDescription: str | None = None
    TriggeredBy: str | None = None
    Type: str | None = None
    WaitUntil: AwareDatetime | None = None


class FieldDiff(BaseModel):
    Annotations: list[str] | None = None
    Name: str | None = None
    New: str | None = None
    Old: str | None = None
    Type: str | None = None


class FuzzyMatch(BaseModel):
    ID: str | None = None
    Scope: list[str] | None = None


class FuzzySearchRequest(BaseModel):
    AllowStale: bool | None = None
    AuthToken: str | None = None
    Context: str | None = None
    Filter: str | None = None
    Headers: dict[str, str] | None = None
    Namespace: str | None = None
    NextToken: str | None = None
    Params: dict[str, str] | None = None
    PerPage: int | None = None
    Prefix: str | None = None
    Region: str | None = None
    Reverse: bool | None = None
    Text: str | None = None
    WaitIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    WaitTime: int | None = None


class FuzzySearchResponse(BaseModel):
    KnownLeader: bool | None = None
    LastContact: int | None = None
    LastIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    Matches: dict[str, list[FuzzyMatch]] | None = None
    NextToken: str | None = None
    RequestTime: int | None = None
    Truncations: dict[str, bool] | None = None


class GaugeValue(BaseModel):
    Labels: dict[str, str] | None = None
    Name: str | None = None
    Value: float | None = None


class HostNetworkInfo(BaseModel):
    CIDR: str | None = None
    Interface: str | None = None
    Name: str | None = None
    ReservedPorts: str | None = None


class HostVolumeInfo(BaseModel):
    Path: str | None = None
    ReadOnly: bool | None = None


class JobACL(BaseModel):
    Group: str | None = None
    JobID: str | None = None
    Namespace: str | None = None
    Task: str | None = None


class JobChildrenSummary(BaseModel):
    Dead: int | None = None
    Pending: int | None = None
    Running: int | None = None


class JobDeregisterResponse(BaseModel):
    EvalCreateIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    EvalID: str | None = None
    JobModifyIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    KnownLeader: bool | None = None
    LastContact: int | None = None
    LastIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    NextToken: str | None = None
    RequestTime: int | None = None


class JobDispatchRequest(BaseModel):
    JobID: str | None = None
    Meta: dict[str, str] | None = None
    Payload: Base64Str | None = None


class JobDispatchResponse(BaseModel):
    DispatchedJobID: str | None = None
    EvalCreateIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    EvalID: str | None = None
    JobCreateIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    LastIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    RequestTime: int | None = None


class JobEvaluateRequest(BaseModel):
    EvalOptions_1: Annotated[EvalOptions | None, Field(alias='EvalOptions')] = None
    JobID: str | None = None
    Namespace: str | None = None
    Region: str | None = None
    SecretID: str | None = None


class JobRegisterResponse(BaseModel):
    EvalCreateIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    EvalID: str | None = None
    JobModifyIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    KnownLeader: bool | None = None
    LastContact: int | None = None
    LastIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    NextToken: str | None = None
    RequestTime: int | None = None
    Warnings: str | None = None


class JobRevertRequest(BaseModel):
    ConsulToken: str | None = None
    EnforcePriorVersion: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = (
        None
    )
    JobID: str | None = None
    JobVersion: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    Namespace: str | None = None
    Region: str | None = None
    SecretID: str | None = None
    VaultToken: str | None = None


class JobStabilityRequest(BaseModel):
    JobID: str | None = None
    JobVersion: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    Namespace: str | None = None
    Region: str | None = None
    SecretID: str | None = None
    Stable: bool | None = None


class JobStabilityResponse(BaseModel):
    Index: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None


class JobValidateResponse(BaseModel):
    DriverConfigValidated: bool | None = None
    Error: str | None = None
    ValidationErrors: list[str] | None = None
    Warnings: str | None = None


class JobsParseRequest(BaseModel):
    Canonicalize: bool | None = None
    JobHCL: str | None = None
    hclv1: bool | None = None


class LogConfig(BaseModel):
    MaxFileSizeMB: int | None = None
    MaxFiles: int | None = None


class MigrateStrategy(BaseModel):
    HealthCheck: str | None = None
    HealthyDeadline: int | None = None
    MaxParallel: int | None = None
    MinHealthyTime: int | None = None


class MultiregionRegion(BaseModel):
    Count: int | None = None
    Datacenters: list[str] | None = None
    Meta: dict[str, str] | None = None
    Name: str | None = None


class MultiregionStrategy(BaseModel):
    MaxParallel: int | None = None
    OnFailure: str | None = None


class NamespaceCapabilities(BaseModel):
    DisabledTaskDrivers: list[str] | None = None
    EnabledTaskDrivers: list[str] | None = None


class ReservableCpuCore(RootModel[int]):
    root: Annotated[int, Field(ge=0, le=65535)]


class NodeCpuResources(BaseModel):
    CpuShares: int | None = None
    ReservableCpuCores: list[ReservableCpuCore] | None = None
    TotalCpuCores: Annotated[int | None, Field(ge=0, le=65535)] = None


class NodeDeviceLocality(BaseModel):
    PciBusID: str | None = None


class NodeDiskResources(BaseModel):
    DiskMB: int | None = None


class NodeDrainUpdateResponse(BaseModel):
    EvalCreateIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    EvalIDs: list[str] | None = None
    LastIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    NodeModifyIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    RequestTime: int | None = None


class NodeEligibilityUpdateResponse(BaseModel):
    EvalCreateIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    EvalIDs: list[str] | None = None
    LastIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    NodeModifyIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    RequestTime: int | None = None


class NodeEvent(BaseModel):
    CreateIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    Details: dict[str, str] | None = None
    Message: str | None = None
    Subsystem: str | None = None
    Timestamp: AwareDatetime | None = None


class NodeMemoryResources(BaseModel):
    MemoryMB: int | None = None


class NodePurgeResponse(BaseModel):
    EvalCreateIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    EvalIDs: list[str] | None = None
    NodeModifyIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None


class NodeReservedCpuResources(BaseModel):
    CpuShares: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None


class NodeReservedDiskResources(BaseModel):
    DiskMB: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None


class NodeReservedMemoryResources(BaseModel):
    MemoryMB: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None


class NodeReservedNetworkResources(BaseModel):
    ReservedHostPorts: str | None = None


class NodeReservedResources(BaseModel):
    Cpu: NodeReservedCpuResources | None = None
    Disk: NodeReservedDiskResources | None = None
    Memory: NodeReservedMemoryResources | None = None
    Networks: NodeReservedNetworkResources | None = None


class NodeScoreMeta(BaseModel):
    NodeID: str | None = None
    NormScore: float | None = None
    Scores: dict[str, float] | None = None


class NodeUpdateDrainRequest(BaseModel):
    DrainSpec_1: Annotated[DrainSpec | None, Field(alias='DrainSpec')] = None
    MarkEligible: bool | None = None
    Meta: dict[str, str] | None = None
    NodeID: str | None = None


class NodeUpdateEligibilityRequest(BaseModel):
    Eligibility: str | None = None
    NodeID: str | None = None


class ObjectDiff(BaseModel):
    Fields: list[FieldDiff] | None = None
    Name: str | None = None
    Objects: list[ObjectDiff] | None = None
    Type: str | None = None


class OneTimeToken(BaseModel):
    AccessorID: str | None = None
    CreateIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    ExpiresAt: AwareDatetime | None = None
    ModifyIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    OneTimeSecretID: str | None = None


class OneTimeTokenExchangeRequest(BaseModel):
    OneTimeSecretID: str | None = None


class ParameterizedJobConfig(BaseModel):
    MetaOptional: list[str] | None = None
    MetaRequired: list[str] | None = None
    Payload: str | None = None


class PeriodicConfig(BaseModel):
    Enabled: bool | None = None
    ProhibitOverlap: bool | None = None
    Spec: str | None = None
    SpecType: str | None = None
    TimeZone: str | None = None


class PeriodicForceResponse(BaseModel):
    EvalCreateIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    EvalID: str | None = None
    Index: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None


class PointValue(BaseModel):
    Name: str | None = None
    Points: list[float] | None = None


class Port(BaseModel):
    HostNetwork: str | None = None
    Label: str | None = None
    To: int | None = None
    Value: int | None = None


class PortMapping(BaseModel):
    HostIP: str | None = None
    Label: str | None = None
    To: int | None = None
    Value: int | None = None


class PreemptionConfig(BaseModel):
    BatchSchedulerEnabled: bool | None = None
    ServiceSchedulerEnabled: bool | None = None
    SysBatchSchedulerEnabled: bool | None = None
    SystemSchedulerEnabled: bool | None = None


class Quotas(RootModel[Any]):
    root: Any


class RaftServer(BaseModel):
    Address: str | None = None
    ID: str | None = None
    Leader: bool | None = None
    Node: str | None = None
    RaftProtocol: str | None = None
    Voter: bool | None = None


class RequestedDevice(BaseModel):
    Affinities: list[Affinity] | None = None
    Constraints: list[Constraint] | None = None
    Count: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    Name: str | None = None


class RescheduleEvent(BaseModel):
    PrevAllocID: str | None = None
    PrevNodeID: str | None = None
    RescheduleTime: int | None = None


class ReschedulePolicy(BaseModel):
    Attempts: int | None = None
    Delay: int | None = None
    DelayFunction: str | None = None
    Interval: int | None = None
    MaxDelay: int | None = None
    Unlimited: bool | None = None


class RescheduleTracker(BaseModel):
    Events: list[RescheduleEvent] | None = None


class RestartPolicy(BaseModel):
    Attempts: int | None = None
    Delay: int | None = None
    Interval: int | None = None
    Mode: str | None = None


class SampledValue(BaseModel):
    Count: int | None = None
    Labels: dict[str, str] | None = None
    Max: float | None = None
    Mean: float | None = None
    Min: float | None = None
    Name: str | None = None
    Rate: float | None = None
    Stddev: float | None = None
    Sum: float | None = None


class ScalingEvent(BaseModel):
    Count: int | None = None
    CreateIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    Error: bool | None = None
    EvalID: str | None = None
    Message: str | None = None
    Meta: dict[str, Any] | None = None
    PreviousCount: int | None = None
    Time: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None


class ScalingPolicy(BaseModel):
    CreateIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    Enabled: bool | None = None
    ID: str | None = None
    Max: int | None = None
    Min: int | None = None
    ModifyIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    Namespace: str | None = None
    Policy: dict[str, Any] | None = None
    Target: dict[str, str] | None = None
    Type: str | None = None


class ScalingPolicyListStub(BaseModel):
    CreateIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    Enabled: bool | None = None
    ID: str | None = None
    ModifyIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    Target: dict[str, str] | None = None
    Type: str | None = None


class ScalingRequest(BaseModel):
    Count: int | None = None
    Error: bool | None = None
    Message: str | None = None
    Meta: dict[str, Any] | None = None
    Namespace: str | None = None
    PolicyOverride: bool | None = None
    Region: str | None = None
    SecretID: str | None = None
    Target: dict[str, str] | None = None


class SchedulerAlgorithm(RootModel[str]):
    root: str


class SchedulerConfiguration(BaseModel):
    CreateIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    MemoryOversubscriptionEnabled: bool | None = None
    ModifyIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    PauseEvalBroker: bool | None = None
    PreemptionConfig_1: Annotated[
        PreemptionConfig | None, Field(alias='PreemptionConfig')
    ] = None
    RejectJobRegistration: bool | None = None
    SchedulerAlgorithm: str | None = None


class SchedulerConfigurationResponse(BaseModel):
    KnownLeader: bool | None = None
    LastContact: int | None = None
    LastIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    NextToken: str | None = None
    RequestTime: int | None = None
    SchedulerConfig: SchedulerConfiguration | None = None


class SchedulerSetConfigurationResponse(BaseModel):
    LastIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    RequestTime: int | None = None
    Updated: bool | None = None


class SearchRequest(BaseModel):
    AllowStale: bool | None = None
    AuthToken: str | None = None
    Context: str | None = None
    Filter: str | None = None
    Headers: dict[str, str] | None = None
    Namespace: str | None = None
    NextToken: str | None = None
    Params: dict[str, str] | None = None
    PerPage: int | None = None
    Prefix: str | None = None
    Region: str | None = None
    Reverse: bool | None = None
    WaitIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    WaitTime: int | None = None


class SearchResponse(BaseModel):
    KnownLeader: bool | None = None
    LastContact: int | None = None
    LastIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    Matches: dict[str, list[str]] | None = None
    NextToken: str | None = None
    RequestTime: int | None = None
    Truncations: dict[str, bool] | None = None


class ServerHealth(BaseModel):
    Address: str | None = None
    Healthy: bool | None = None
    ID: str | None = None
    LastContact: int | None = None
    LastIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    LastTerm: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    Leader: bool | None = None
    Name: str | None = None
    SerfStatus: str | None = None
    StableSince: AwareDatetime | None = None
    Version: str | None = None
    Voter: bool | None = None


class ServiceCheck(BaseModel):
    AddressMode: str | None = None
    Advertise: str | None = None
    Args: list[str] | None = None
    Body: str | None = None
    CheckRestart_1: Annotated[CheckRestart | None, Field(alias='CheckRestart')] = None
    Command: str | None = None
    Expose: bool | None = None
    FailuresBeforeCritical: int | None = None
    GRPCService: str | None = None
    GRPCUseTLS: bool | None = None
    Header: dict[str, list[str]] | None = None
    InitialStatus: str | None = None
    Interval: int | None = None
    Method: str | None = None
    Name: str | None = None
    OnUpdate: str | None = None
    Path: str | None = None
    PortLabel: str | None = None
    Protocol: str | None = None
    SuccessBeforePassing: int | None = None
    TLSSkipVerify: bool | None = None
    TaskName: str | None = None
    Timeout: int | None = None
    Type: str | None = None


class ServiceRegistration(BaseModel):
    Address: str | None = None
    AllocID: str | None = None
    CreateIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    Datacenter: str | None = None
    ID: str | None = None
    JobID: str | None = None
    ModifyIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    Namespace: str | None = None
    NodeID: str | None = None
    Port: int | None = None
    ServiceName: str | None = None
    Tags: list[str] | None = None


class SpreadTarget(BaseModel):
    Percent: Annotated[int | None, Field(ge=0, le=255)] = None
    Value: str | None = None


class TaskArtifact(BaseModel):
    GetterHeaders: dict[str, str] | None = None
    GetterMode: str | None = None
    GetterOptions: dict[str, str] | None = None
    GetterSource: str | None = None
    RelativeDest: str | None = None


class TaskCSIPluginConfig(BaseModel):
    HealthTimeout: int | None = None
    ID: str | None = None
    MountDir: str | None = None
    StagePublishBaseDir: str | None = None
    Type: str | None = None


class TaskDiff(BaseModel):
    Annotations: list[str] | None = None
    Fields: list[FieldDiff] | None = None
    Name: str | None = None
    Objects: list[ObjectDiff] | None = None
    Type: str | None = None


class TaskEvent(BaseModel):
    Details: dict[str, str] | None = None
    DiskLimit: int | None = None
    DiskSize: int | None = None
    DisplayMessage: str | None = None
    DownloadError: str | None = None
    DriverError: str | None = None
    DriverMessage: str | None = None
    ExitCode: int | None = None
    FailedSibling: str | None = None
    FailsTask: bool | None = None
    GenericSource: str | None = None
    KillError: str | None = None
    KillReason: str | None = None
    KillTimeout: int | None = None
    Message: str | None = None
    RestartReason: str | None = None
    SetupError: str | None = None
    Signal: int | None = None
    StartDelay: int | None = None
    TaskSignal: str | None = None
    TaskSignalReason: str | None = None
    Time: int | None = None
    Type: str | None = None
    ValidationError: str | None = None
    VaultError: str | None = None


UpdatesAdditionalProperty = TypeAliasType(
    "UpdatesAdditionalProperty", Annotated[int, Field(ge=0, le=18446744073709552000)]
)


class TaskGroupDiff(BaseModel):
    Fields: list[FieldDiff] | None = None
    Name: str | None = None
    Objects: list[ObjectDiff] | None = None
    Tasks: list[TaskDiff] | None = None
    Type: str | None = None
    Updates: dict[str, UpdatesAdditionalProperty] | None = None


class TaskGroupScaleStatus(BaseModel):
    Desired: int | None = None
    Events: list[ScalingEvent] | None = None
    Healthy: int | None = None
    Placed: int | None = None
    Running: int | None = None
    Unhealthy: int | None = None


class TaskGroupSummary(BaseModel):
    Complete: int | None = None
    Failed: int | None = None
    Lost: int | None = None
    Queued: int | None = None
    Running: int | None = None
    Starting: int | None = None
    Unknown: int | None = None


class TaskHandle(BaseModel):
    DriverState: Base64Str | None = None
    Version: int | None = None


class TaskLifecycle(BaseModel):
    Hook: str | None = None
    Sidecar: bool | None = None


class TaskState(BaseModel):
    Events: list[TaskEvent] | None = None
    Failed: bool | None = None
    FinishedAt: AwareDatetime | None = None
    LastRestart: AwareDatetime | None = None
    Restarts: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    StartedAt: AwareDatetime | None = None
    State: str | None = None
    TaskHandle_1: Annotated[TaskHandle | None, Field(alias='TaskHandle')] = None


class Time(RootModel[AwareDatetime]):
    root: AwareDatetime


class UpdateStrategy(BaseModel):
    AutoPromote: bool | None = None
    AutoRevert: bool | None = None
    Canary: int | None = None
    HealthCheck: str | None = None
    HealthyDeadline: int | None = None
    MaxParallel: int | None = None
    MinHealthyTime: int | None = None
    ProgressDeadline: int | None = None
    Stagger: int | None = None


class VariableItems(RootModel[dict[str, str]]):
    root: dict[str, str]


class VariableMetadata(BaseModel):
    CreateIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    CreateTime: int | None = None
    ModifyIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    ModifyTime: int | None = None
    Namespace: str | None = None
    Path: str | None = None


class Vault(BaseModel):
    ChangeMode: str | None = None
    ChangeSignal: str | None = None
    Env: bool | None = None
    Namespace: str | None = None
    Policies: list[str] | None = None


class VolumeMount(BaseModel):
    Destination: str | None = None
    PropagationMode: str | None = None
    ReadOnly: bool | None = None
    Volume: str | None = None


class VolumeRequest(BaseModel):
    AccessMode: str | None = None
    AttachmentMode: str | None = None
    MountOptions: CSIMountOptions | None = None
    Name: str | None = None
    PerAlloc: bool | None = None
    ReadOnly: bool | None = None
    Source: str | None = None
    Type: str | None = None


class WaitConfig(BaseModel):
    Max: int | None = None
    Min: int | None = None


class Float32(RootModel[float]):
    root: float


class Float64(RootModel[float]):
    root: float


class Int(RootModel[int]):
    root: int


class Int8(RootModel[int]):
    root: Annotated[int, Field(ge=-128, le=127)]


class Int32(RootModel[int]):
    root: int


class Int64(RootModel[int]):
    root: int


class Uint(RootModel[int]):
    root: Annotated[int, Field(ge=0)]


class Uint8(RootModel[int]):
    root: Annotated[int, Field(ge=0, le=255)]


class Uint16(RootModel[int]):
    root: Annotated[int, Field(ge=0, le=65535)]


class Uint64(RootModel[int]):
    root: Annotated[int, Field(ge=0, le=18446744073709552000)]


class ACLPolicy(BaseModel):
    CreateIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    Description: str | None = None
    JobACL_1: Annotated[JobACL | None, Field(alias='JobACL')] = None
    ModifyIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    Name: str | None = None
    Rules: str | None = None


class ACLToken(BaseModel):
    AccessorID: str | None = None
    CreateIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    CreateTime: AwareDatetime | None = None
    ExpirationTTL: int | None = None
    ExpirationTime: AwareDatetime | None = None
    Global: bool | None = None
    ModifyIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    Name: str | None = None
    Policies: list[str] | None = None
    Roles: list[ACLTokenRoleLink] | None = None
    SecretID: str | None = None
    Type: str | None = None


class ACLTokenListStub(BaseModel):
    AccessorID: str | None = None
    CreateIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    CreateTime: AwareDatetime | None = None
    Global: bool | None = None
    ModifyIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    Name: str | None = None
    Policies: list[str] | None = None
    Roles: list[ACLTokenRoleLink] | None = None
    Type: str | None = None
    expiration_time: AwareDatetime | None = None


class CSINodeInfo(BaseModel):
    AccessibleTopology: CSITopology | None = None
    ID: str | None = None
    MaxVolumes: int | None = None
    RequiresNodeStageVolume: bool | None = None
    SupportsCondition: bool | None = None
    SupportsExpand: bool | None = None
    SupportsStats: bool | None = None


class ConsulExposeConfig(BaseModel):
    Path: list[ConsulExposePath] | None = None


class ConsulIngressListener(BaseModel):
    Port: int | None = None
    Protocol: str | None = None
    Services: list[ConsulIngressService] | None = None


class ConsulProxy(BaseModel):
    Config: dict[str, Any] | None = None
    ExposeConfig: ConsulExposeConfig | None = None
    LocalServiceAddress: str | None = None
    LocalServicePort: int | None = None
    Upstreams: list[ConsulUpstream] | None = None


class ConsulSidecarService(BaseModel):
    DisableDefaultTCPCheck: bool | None = None
    Port: str | None = None
    Proxy: ConsulProxy | None = None
    Tags: list[str] | None = None


class Deployment(BaseModel):
    CreateIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    ID: str | None = None
    IsMultiregion: bool | None = None
    JobCreateIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    JobID: str | None = None
    JobModifyIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    JobSpecModifyIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = (
        None
    )
    JobVersion: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    ModifyIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    Namespace: str | None = None
    Status: str | None = None
    StatusDescription: str | None = None
    TaskGroups: dict[str, DeploymentState] | None = None


class JobDiff(BaseModel):
    Fields: list[FieldDiff] | None = None
    ID: str | None = None
    Objects: list[ObjectDiff] | None = None
    TaskGroups: list[TaskGroupDiff] | None = None
    Type: str | None = None


class JobScaleStatusResponse(BaseModel):
    JobCreateIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    JobID: str | None = None
    JobModifyIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    JobStopped: bool | None = None
    Namespace: str | None = None
    TaskGroups: dict[str, TaskGroupScaleStatus] | None = None


class JobSummary(BaseModel):
    Children: JobChildrenSummary | None = None
    CreateIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    JobID: str | None = None
    ModifyIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    Namespace: str | None = None
    Summary: dict[str, TaskGroupSummary] | None = None


class MetricsSummary(BaseModel):
    Counters: list[SampledValue] | None = None
    Gauges: list[GaugeValue] | None = None
    Points: list[PointValue] | None = None
    Samples: list[SampledValue] | None = None
    Timestamp: str | None = None


class Multiregion(BaseModel):
    Regions: list[MultiregionRegion] | None = None
    Strategy: MultiregionStrategy | None = None


class Namespace(BaseModel):
    Capabilities: NamespaceCapabilities | None = None
    CreateIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    Description: str | None = None
    Meta: dict[str, str] | None = None
    ModifyIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    Name: str | None = None
    Quota: str | None = None


class NetworkResource(BaseModel):
    CIDR: str | None = None
    DNS: DNSConfig | None = None
    Device: str | None = None
    DynamicPorts: list[Port] | None = None
    Hostname: str | None = None
    IP: str | None = None
    MBits: int | None = None
    Mode: str | None = None
    ReservedPorts: list[Port] | None = None


class NodeDevice(BaseModel):
    HealthDescription: str | None = None
    Healthy: bool | None = None
    ID: str | None = None
    Locality: NodeDeviceLocality | None = None


class NodeDeviceResource(BaseModel):
    Attributes: dict[str, Attribute] | None = None
    Instances: list[NodeDevice] | None = None
    Name: str | None = None
    Type: str | None = None
    Vendor: str | None = None


class NodeResources(BaseModel):
    Cpu: NodeCpuResources | None = None
    Devices: list[NodeDeviceResource] | None = None
    Disk: NodeDiskResources | None = None
    MaxDynamicPort: int | None = None
    Memory: NodeMemoryResources | None = None
    MinDynamicPort: int | None = None
    Networks: list[NetworkResource] | None = None


class OperatorHealthReply(BaseModel):
    FailureTolerance: int | None = None
    Healthy: bool | None = None
    Servers: list[ServerHealth] | None = None


class RaftConfiguration(BaseModel):
    Index: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    Servers: list[RaftServer] | None = None


class Resources(BaseModel):
    CPU: int | None = None
    Cores: int | None = None
    Devices: list[RequestedDevice] | None = None
    DiskMB: int | None = None
    IOPS: int | None = None
    MemoryMB: int | None = None
    MemoryMaxMB: int | None = None
    Networks: list[NetworkResource] | None = None


class SidecarTask(BaseModel):
    Config: dict[str, Any] | None = None
    Driver: str | None = None
    Env: dict[str, str] | None = None
    KillSignal: str | None = None
    KillTimeout: int | None = None
    LogConfig_1: Annotated[LogConfig | None, Field(alias='LogConfig')] = None
    Meta: dict[str, str] | None = None
    Name: str | None = None
    Resources_1: Annotated[Resources | None, Field(alias='Resources')] = None
    ShutdownDelay: int | None = None
    User: str | None = None


class Spread(BaseModel):
    Attribute: str | None = None
    SpreadTarget_1: Annotated[
        list[SpreadTarget] | None, Field(alias='SpreadTarget')
    ] = None
    Weight: Annotated[int | None, Field(ge=-128, le=127)] = None


class Template(BaseModel):
    ChangeMode: str | None = None
    ChangeScript_1: Annotated[ChangeScript | None, Field(alias='ChangeScript')] = None
    ChangeSignal: str | None = None
    DestPath: str | None = None
    EmbeddedTmpl: str | None = None
    Envvars: bool | None = None
    Gid: int | None = None
    LeftDelim: str | None = None
    Perms: str | None = None
    RightDelim: str | None = None
    SourcePath: str | None = None
    Splay: int | None = None
    Uid: int | None = None
    VaultGrace: int | None = None
    Wait: WaitConfig | None = None


class Variable(BaseModel):
    CreateIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    CreateTime: int | None = None
    Items: VariableItems | None = None
    ModifyIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    ModifyTime: int | None = None
    Namespace: str | None = None
    Path: str | None = None


class AllocatedSharedResources(BaseModel):
    DiskMB: int | None = None
    Networks: list[NetworkResource] | None = None
    Ports: list[PortMapping] | None = None


class AllocatedTaskResources(BaseModel):
    Cpu: AllocatedCpuResources | None = None
    Devices: list[AllocatedDeviceResource] | None = None
    Memory: AllocatedMemoryResources | None = None
    Networks: list[NetworkResource] | None = None


class AllocationMetric(BaseModel):
    AllocationTime: int | None = None
    ClassExhausted: dict[str, int] | None = None
    ClassFiltered: dict[str, int] | None = None
    CoalescedFailures: int | None = None
    ConstraintFiltered: dict[str, int] | None = None
    DimensionExhausted: dict[str, int] | None = None
    NodesAvailable: dict[str, int] | None = None
    NodesEvaluated: int | None = None
    NodesExhausted: int | None = None
    NodesFiltered: int | None = None
    QuotaExhausted: list[str] | None = None
    ResourcesExhausted: dict[str, Resources] | None = None
    ScoreMetaData: list[NodeScoreMeta] | None = None
    Scores: dict[str, float] | None = None


class CSIInfo(BaseModel):
    AllocID: str | None = None
    ControllerInfo: CSIControllerInfo | None = None
    HealthDescription: str | None = None
    Healthy: bool | None = None
    NodeInfo: CSINodeInfo | None = None
    PluginID: str | None = None
    RequiresControllerPlugin: bool | None = None
    RequiresTopologies: bool | None = None
    UpdateTime: AwareDatetime | None = None


class ConsulIngressConfigEntry(BaseModel):
    Listeners: list[ConsulIngressListener] | None = None
    TLS: ConsulGatewayTLSConfig | None = None


class Evaluation(BaseModel):
    AnnotatePlan: bool | None = None
    BlockedEval: str | None = None
    ClassEligibility: dict[str, bool] | None = None
    CreateIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    CreateTime: int | None = None
    DeploymentID: str | None = None
    EscapedComputedClass: bool | None = None
    FailedTGAllocs: dict[str, AllocationMetric] | None = None
    ID: str | None = None
    JobID: str | None = None
    JobModifyIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    ModifyIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    ModifyTime: int | None = None
    Namespace: str | None = None
    NextEval: str | None = None
    NodeID: str | None = None
    NodeModifyIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    PreviousEval: str | None = None
    Priority: int | None = None
    QueuedAllocations: dict[str, int] | None = None
    QuotaLimitReached: str | None = None
    RelatedEvals: list[EvaluationStub] | None = None
    SnapshotIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    Status: str | None = None
    StatusDescription: str | None = None
    TriggeredBy: str | None = None
    Type: str | None = None
    Wait: int | None = None
    WaitUntil: AwareDatetime | None = None


class JobListStub(BaseModel):
    CreateIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    Datacenters: list[str] | None = None
    ID: str | None = None
    JobModifyIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    JobSummary_1: Annotated[JobSummary | None, Field(alias='JobSummary')] = None
    ModifyIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    Name: str | None = None
    Namespace: str | None = None
    ParameterizedJob: bool | None = None
    ParentID: str | None = None
    Periodic: bool | None = None
    Priority: int | None = None
    Status: str | None = None
    StatusDescription: str | None = None
    Stop: bool | None = None
    SubmitTime: int | None = None
    Type: str | None = None


class Node(BaseModel):
    Attributes: dict[str, str] | None = None
    CSIControllerPlugins: dict[str, CSIInfo] | None = None
    CSINodePlugins: dict[str, CSIInfo] | None = None
    CgroupParent: str | None = None
    CreateIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    Datacenter: str | None = None
    Drain: bool | None = None
    DrainStrategy_1: Annotated[DrainStrategy | None, Field(alias='DrainStrategy')] = (
        None
    )
    Drivers: dict[str, DriverInfo] | None = None
    Events: list[NodeEvent] | None = None
    HTTPAddr: str | None = None
    HostNetworks: dict[str, HostNetworkInfo] | None = None
    HostVolumes: dict[str, HostVolumeInfo] | None = None
    ID: str | None = None
    LastDrain: DrainMetadata | None = None
    Links: dict[str, str] | None = None
    Meta: dict[str, str] | None = None
    ModifyIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    Name: str | None = None
    NodeClass: str | None = None
    NodeResources_1: Annotated[NodeResources | None, Field(alias='NodeResources')] = (
        None
    )
    Reserved: Resources | None = None
    ReservedResources: NodeReservedResources | None = None
    Resources_1: Annotated[Resources | None, Field(alias='Resources')] = None
    SchedulingEligibility: str | None = None
    Status: str | None = None
    StatusDescription: str | None = None
    StatusUpdatedAt: int | None = None
    TLSEnabled: bool | None = None


class NodeListStub(BaseModel):
    Address: str | None = None
    Attributes: dict[str, str] | None = None
    CreateIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    Datacenter: str | None = None
    Drain: bool | None = None
    Drivers: dict[str, DriverInfo] | None = None
    ID: str | None = None
    LastDrain: DrainMetadata | None = None
    ModifyIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    Name: str | None = None
    NodeClass: str | None = None
    NodeResources_1: Annotated[NodeResources | None, Field(alias='NodeResources')] = (
        None
    )
    ReservedResources: NodeReservedResources | None = None
    SchedulingEligibility: str | None = None
    Status: str | None = None
    StatusDescription: str | None = None
    Version: str | None = None


class QuotaLimit(BaseModel):
    Hash: Base64Str | None = None
    Region: str | None = None
    RegionLimit: Resources | None = None
    VariablesLimit: int | None = None


class QuotaSpec(BaseModel):
    CreateIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    Description: str | None = None
    Limits: list[QuotaLimit] | None = None
    ModifyIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    Name: str | None = None


class AllocatedResources(BaseModel):
    Shared: AllocatedSharedResources | None = None
    Tasks: dict[str, AllocatedTaskResources] | None = None


class AllocationListStub(BaseModel):
    AllocatedResources_1: Annotated[
        AllocatedResources | None, Field(alias='AllocatedResources')
    ] = None
    ClientDescription: str | None = None
    ClientStatus: str | None = None
    CreateIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    CreateTime: int | None = None
    DeploymentStatus: AllocDeploymentStatus | None = None
    DesiredDescription: str | None = None
    DesiredStatus: str | None = None
    EvalID: str | None = None
    FollowupEvalID: str | None = None
    ID: str | None = None
    JobID: str | None = None
    JobType: str | None = None
    JobVersion: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    ModifyIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    ModifyTime: int | None = None
    Name: str | None = None
    Namespace: str | None = None
    NodeID: str | None = None
    NodeName: str | None = None
    PreemptedAllocations: list[str] | None = None
    PreemptedByAllocation: str | None = None
    RescheduleTracker_1: Annotated[
        RescheduleTracker | None, Field(alias='RescheduleTracker')
    ] = None
    TaskGroup: str | None = None
    TaskStates: dict[str, TaskState] | None = None


class CSIPlugin(BaseModel):
    Allocations: list[AllocationListStub] | None = None
    ControllerRequired: bool | None = None
    Controllers: dict[str, CSIInfo] | None = None
    ControllersExpected: int | None = None
    ControllersHealthy: int | None = None
    CreateIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    ID: str | None = None
    ModifyIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    Nodes: dict[str, CSIInfo] | None = None
    NodesExpected: int | None = None
    NodesHealthy: int | None = None
    Provider: str | None = None
    Version: str | None = None


class ConsulGateway(BaseModel):
    Ingress: ConsulIngressConfigEntry | None = None
    Mesh: Any | None = None
    Proxy: ConsulGatewayProxy | None = None
    Terminating: ConsulTerminatingConfigEntry | None = None


class PlanAnnotations(BaseModel):
    DesiredTGUpdates: dict[str, DesiredUpdates] | None = None
    PreemptedAllocs: list[AllocationListStub] | None = None


class ConsulConnect(BaseModel):
    Gateway: ConsulGateway | None = None
    Native: bool | None = None
    SidecarService: ConsulSidecarService | None = None
    SidecarTask_1: Annotated[SidecarTask | None, Field(alias='SidecarTask')] = None


class JobPlanResponse(BaseModel):
    Annotations: PlanAnnotations | None = None
    CreatedEvals: list[Evaluation] | None = None
    Diff: JobDiff | None = None
    FailedTGAllocs: dict[str, AllocationMetric] | None = None
    JobModifyIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    NextPeriodicLaunch: AwareDatetime | None = None
    Warnings: str | None = None


class Service(BaseModel):
    Address: str | None = None
    AddressMode: str | None = None
    CanaryMeta: dict[str, str] | None = None
    CanaryTags: list[str] | None = None
    CheckRestart_1: Annotated[CheckRestart | None, Field(alias='CheckRestart')] = None
    Checks: list[ServiceCheck] | None = None
    Connect: ConsulConnect | None = None
    EnableTagOverride: bool | None = None
    Meta: dict[str, str] | None = None
    Name: str | None = None
    OnUpdate: str | None = None
    PortLabel: str | None = None
    Provider: str | None = None
    TaggedAddresses: dict[str, str] | None = None
    Tags: list[str] | None = None
    TaskName: str | None = None


class Task(BaseModel):
    Affinities: list[Affinity] | None = None
    Artifacts: list[TaskArtifact] | None = None
    CSIPluginConfig: TaskCSIPluginConfig | None = None
    Config: dict[str, Any] | None = None
    Constraints: list[Constraint] | None = None
    DispatchPayload: DispatchPayloadConfig | None = None
    Driver: str | None = None
    Env: dict[str, str] | None = None
    KillSignal: str | None = None
    KillTimeout: int | None = None
    Kind: str | None = None
    Leader: bool | None = None
    Lifecycle: TaskLifecycle | None = None
    LogConfig_1: Annotated[LogConfig | None, Field(alias='LogConfig')] = None
    Meta: dict[str, str] | None = None
    Name: str | None = None
    Resources_1: Annotated[Resources | None, Field(alias='Resources')] = None
    RestartPolicy_1: Annotated[RestartPolicy | None, Field(alias='RestartPolicy')] = (
        None
    )
    ScalingPolicies: list[ScalingPolicy] | None = None
    Services: list[Service] | None = None
    ShutdownDelay: int | None = None
    Templates: list[Template] | None = None
    User: str | None = None
    Vault_1: Annotated[Vault | None, Field(alias='Vault')] = None
    VolumeMounts: list[VolumeMount] | None = None


class TaskGroup(BaseModel):
    Affinities: list[Affinity] | None = None
    Constraints: list[Constraint] | None = None
    Consul_1: Annotated[Consul | None, Field(alias='Consul')] = None
    Count: int | None = None
    EphemeralDisk_1: Annotated[EphemeralDisk | None, Field(alias='EphemeralDisk')] = (
        None
    )
    MaxClientDisconnect: int | None = None
    Meta: dict[str, str] | None = None
    Migrate: MigrateStrategy | None = None
    Name: str | None = None
    Networks: list[NetworkResource] | None = None
    ReschedulePolicy_1: Annotated[
        ReschedulePolicy | None, Field(alias='ReschedulePolicy')
    ] = None
    RestartPolicy_1: Annotated[RestartPolicy | None, Field(alias='RestartPolicy')] = (
        None
    )
    Scaling: ScalingPolicy | None = None
    Services: list[Service] | None = None
    ShutdownDelay: int | None = None
    Spreads: list[Spread] | None = None
    StopAfterClientDisconnect: int | None = None
    Tasks: list[Task] | None = None
    Update: UpdateStrategy | None = None
    Volumes: dict[str, VolumeRequest] | None = None


class Job(BaseModel):
    Affinities: list[Affinity] | None = None
    AllAtOnce: bool | None = None
    Constraints: list[Constraint] | None = None
    ConsulNamespace: str | None = None
    ConsulToken: str | None = None
    CreateIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    Datacenters: list[str] | None = None
    DispatchIdempotencyToken: str | None = None
    Dispatched: bool | None = None
    ID: str | None = None
    JobModifyIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    Meta: dict[str, str] | None = None
    Migrate: MigrateStrategy | None = None
    ModifyIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    Multiregion_1: Annotated[Multiregion | None, Field(alias='Multiregion')] = None
    Name: str | None = None
    Namespace: str | None = None
    NomadTokenID: str | None = None
    ParameterizedJob: ParameterizedJobConfig | None = None
    ParentID: str | None = None
    Payload: Base64Str | None = None
    Periodic: PeriodicConfig | None = None
    Priority: int | None = None
    Region: str | None = None
    Reschedule: ReschedulePolicy | None = None
    Spreads: list[Spread] | None = None
    Stable: bool | None = None
    Status: str | None = None
    StatusDescription: str | None = None
    Stop: bool | None = None
    SubmitTime: int | None = None
    TaskGroups: list[TaskGroup] | None = None
    Type: str | None = None
    Update: UpdateStrategy | None = None
    VaultNamespace: str | None = None
    VaultToken: str | None = None
    Version: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None


class JobPlanRequest(BaseModel):
    Diff: bool | None = None
    Job_1: Annotated[Job | None, Field(alias='Job')] = None
    Namespace: str | None = None
    PolicyOverride: bool | None = None
    Region: str | None = None
    SecretID: str | None = None


class JobRegisterRequest(BaseModel):
    EnforceIndex: bool | None = None
    EvalPriority: int | None = None
    Job_1: Annotated[Job | None, Field(alias='Job')] = None
    JobModifyIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    Namespace: str | None = None
    PolicyOverride: bool | None = None
    PreserveCounts: bool | None = None
    Region: str | None = None
    SecretID: str | None = None


class JobValidateRequest(BaseModel):
    Job_1: Annotated[Job | None, Field(alias='Job')] = None
    Namespace: str | None = None
    Region: str | None = None
    SecretID: str | None = None


class JobVersionsResponse(BaseModel):
    Diffs: list[JobDiff] | None = None
    KnownLeader: bool | None = None
    LastContact: int | None = None
    LastIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    NextToken: str | None = None
    RequestTime: int | None = None
    Versions: list[Job] | None = None


class Allocation(BaseModel):
    AllocModifyIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    AllocatedResources_1: Annotated[
        AllocatedResources | None, Field(alias='AllocatedResources')
    ] = None
    ClientDescription: str | None = None
    ClientStatus: str | None = None
    CreateIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    CreateTime: int | None = None
    DeploymentID: str | None = None
    DeploymentStatus: AllocDeploymentStatus | None = None
    DesiredDescription: str | None = None
    DesiredStatus: str | None = None
    DesiredTransition_1: Annotated[
        DesiredTransition | None, Field(alias='DesiredTransition')
    ] = None
    EvalID: str | None = None
    FollowupEvalID: str | None = None
    ID: str | None = None
    Job_1: Annotated[Job | None, Field(alias='Job')] = None
    JobID: str | None = None
    Metrics: AllocationMetric | None = None
    ModifyIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    ModifyTime: int | None = None
    Name: str | None = None
    Namespace: str | None = None
    NextAllocation: str | None = None
    NodeID: str | None = None
    NodeName: str | None = None
    PreemptedAllocations: list[str] | None = None
    PreemptedByAllocation: str | None = None
    PreviousAllocation: str | None = None
    RescheduleTracker_1: Annotated[
        RescheduleTracker | None, Field(alias='RescheduleTracker')
    ] = None
    Resources_1: Annotated[Resources | None, Field(alias='Resources')] = None
    Services: dict[str, str] | None = None
    TaskGroup: str | None = None
    TaskResources: dict[str, Resources] | None = None
    TaskStates: dict[str, TaskState] | None = None


class CSIVolume(BaseModel):
    AccessMode: str | None = None
    Allocations: list[AllocationListStub] | None = None
    AttachmentMode: str | None = None
    Capacity: int | None = None
    CloneID: str | None = None
    Context: dict[str, str] | None = None
    ControllerRequired: bool | None = None
    ControllersExpected: int | None = None
    ControllersHealthy: int | None = None
    CreateIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    ExternalID: str | None = None
    ID: str | None = None
    ModifyIndex: Annotated[int | None, Field(ge=0, le=18446744073709552000)] = None
    MountOptions: CSIMountOptions | None = None
    Name: str | None = None
    Namespace: str | None = None
    NodesExpected: int | None = None
    NodesHealthy: int | None = None
    Parameters: dict[str, str] | None = None
    PluginID: str | None = None
    Provider: str | None = None
    ProviderVersion: str | None = None
    ReadAllocs: dict[str, Allocation] | None = None
    RequestedCapabilities: list[CSIVolumeCapability] | None = None
    RequestedCapacityMax: int | None = None
    RequestedCapacityMin: int | None = None
    RequestedTopologies: CSITopologyRequest | None = None
    ResourceExhausted: AwareDatetime | None = None
    Schedulable: bool | None = None
    Secrets: CSISecrets | None = None
    SnapshotID: str | None = None
    Topologies: list[CSITopology] | None = None
    WriteAllocs: dict[str, Allocation] | None = None


class CSIVolumeCreateRequest(BaseModel):
    Namespace: str | None = None
    Region: str | None = None
    SecretID: str | None = None
    Volumes: list[CSIVolume] | None = None


class CSIVolumeRegisterRequest(BaseModel):
    Namespace: str | None = None
    Region: str | None = None
    SecretID: str | None = None
    Volumes: list[CSIVolume] | None = None


ObjectDiff.model_rebuild()
