name: Python package

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-python@v7
        with:
          python-version: "3.13"

      - name: Install Poetry
        run: pipx install poetry

      - name: Publish
        run: poetry publish --build --username=__token__ --password=${{ secrets.PYPI_TOKEN }}
