name: Python package
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8.13

      - name: Run image
        uses: abatilo/actions-poetry@v2.1.26
        with:
          poetry-version: 1.2.0
      - name: View poetry --help
        run: poetry --version
      - name: Publish
        run: poetry --build --password=${{ secrets.PYPI_TOKEN }} --username=__token__
